name: Workflow Teste

on:
  push:
  schedule:
    - cron: '0 * * * *' 

jobs:
  log-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "Ação executada" 
    - run: |
        if [ "$(date +%H)" = "00" ]; then
          echo "Ação executada"
        fi # This script checks if the current hour is 00 (midnight) and logs "Ação executada"